In [74]:
import requests
import json
import pandas as pd
import datetime as dt
import numpy as np

In [75]:
cfdata = pd.read_csv('./data/cfdata.csv')
cfdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24541 entries, 0 to 24540
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   24541 non-null  int64
 1   APVPERMYMD   24541 non-null  object
 2   TRDSTATEGBN  24541 non-null  int64
 3   TRDSTATENM   24541 non-null  object
 4   DCBYMD       8624 non-null   object
 5   SITEAREA     23486 non-null  object
 6   BPLCNM       24541 non-null  object
 7   X            24541 non-null  float64
 8   Y            24541 non-null  float64
 9   region       24541 non-null  object
 10  ADDR         24541 non-null  object
dtypes: float64(2), int64(2), object(7)
memory usage: 2.1+ MB

In [ ]:
new_add=[]

for i in range(len(cfdata['RDNWHLADDR'])):
    new_add.append(cfdata['RDNWHLADDR'][i].split(',')[0])

print(len(new_add))
print(len(cfdata['RDNWHLADDR']))

In [26]:
cfdata['ADDR'] = new_add

In [30]:
#cfdata = cfdata.drop(['Unnamed: 0'],axis=1)
#cfdata = cfdata.drop(['RDNWHLADDR'],axis=1)

In [ ]:
cfdata[25]

In [32]:
cfdata.to_csv('./data/cfdata.csv',encoding='utf-8')

In [48]:
cfdata['ADDR'][0]

'서울특별시 강동구 양재대로87길 11 (성내동)'

In [43]:
import re

In [65]:
#p = re.compile('^"("\w')

In [66]:
#p.findall(cfdata['ADDR'][0])

In [76]:
new_addr=[]

for i in range(len(cfdata['ADDR'])):
    new_addr.append(cfdata['ADDR'][i].split('(')[0])

print(len(new_addr))
print(len(cfdata['ADDR']))

24541
24541

In [77]:
cfdata['ADDR'] = new_addr

In [78]:
cfdata

,Unnamed: 0,APVPERMYMD,TRDSTATEGBN,TRDSTATENM,DCBYMD,SITEAREA,BPLCNM,X,Y,region,ADDR
0,0,2013-11-13,3,폐업,2017-10-11,22.53,탭플레이 커피,127.134306,37.525438,강동구,서울특별시 강동구 양재대로87길 11
1,1,2015-07-08,3,폐업,2017-07-10,22.00,아카페,127.131877,37.539416,강동구,서울특별시 강동구 진황도로27길 23
2,2,2014-03-20,3,폐업,2017-07-17,74.21,CAFE TENUTO 테누토,127.146158,37.550130,강동구,서울특별시 강동구 구천면로 428
3,3,2014-12-05,3,폐업,2017-06-02,337.19,할리스커피 올림픽공원북문점,127.129210,37.524394,강동구,서울특별시 강동구 강동대로 205
4,4,2013-01-03,3,폐업,2017-05-18,30.00,도우드림,127.140339,37.531725,강동구,서울특별시 강동구 풍성로63길 84
...,...,...,...,...,...,...,...,...,...,...,...
24536,24536,2011-03-02,1,영업/정상,NaN,98.10,카페 엘리,127.032416,37.485785,서초구,서울특별시 서초구 강남대로39길 15-7
24537,24537,2010-09-16,1,영업/정상,NaN,50.00,카페레즈,127.041496,37.481075,서초구,서울특별시 서초구 바우뫼로41길 8
24538,24538,2010-05-27,1,영업/정상,NaN,142.50,마켓 비노플라워,126.996156,37.498874,서초구,서울특별시 서초구 사평대로 106
24539,24539,2009-10-29,1,영업/정상,NaN,62.00,까페원더,127.039916,37.484342,서초구,서울특별시 서초구 바우뫼로41길 88
24540,24540,2013-12-20,1,영업/정상,NaN,66.84,크래프트카페(래경공방),126.982964,37.587294,종로구,서울특별시 종로구 북촌로 137

In [79]:
cfdata = cfdata.drop(['Unnamed: 0'],axis=1)

In [80]:
cfdata

,APVPERMYMD,TRDSTATEGBN,TRDSTATENM,DCBYMD,SITEAREA,BPLCNM,X,Y,region,ADDR
0,2013-11-13,3,폐업,2017-10-11,22.53,탭플레이 커피,127.134306,37.525438,강동구,서울특별시 강동구 양재대로87길 11
1,2015-07-08,3,폐업,2017-07-10,22.00,아카페,127.131877,37.539416,강동구,서울특별시 강동구 진황도로27길 23
2,2014-03-20,3,폐업,2017-07-17,74.21,CAFE TENUTO 테누토,127.146158,37.550130,강동구,서울특별시 강동구 구천면로 428
3,2014-12-05,3,폐업,2017-06-02,337.19,할리스커피 올림픽공원북문점,127.129210,37.524394,강동구,서울특별시 강동구 강동대로 205
4,2013-01-03,3,폐업,2017-05-18,30.00,도우드림,127.140339,37.531725,강동구,서울특별시 강동구 풍성로63길 84
...,...,...,...,...,...,...,...,...,...,...
24536,2011-03-02,1,영업/정상,NaN,98.10,카페 엘리,127.032416,37.485785,서초구,서울특별시 서초구 강남대로39길 15-7
24537,2010-09-16,1,영업/정상,NaN,50.00,카페레즈,127.041496,37.481075,서초구,서울특별시 서초구 바우뫼로41길 8
24538,2010-05-27,1,영업/정상,NaN,142.50,마켓 비노플라워,126.996156,37.498874,서초구,서울특별시 서초구 사평대로 106
24539,2009-10-29,1,영업/정상,NaN,62.00,까페원더,127.039916,37.484342,서초구,서울특별시 서초구 바우뫼로41길 88
24540,2013-12-20,1,영업/정상,NaN,66.84,크래프트카페(래경공방),126.982964,37.587294,종로구,서울특별시 종로구 북촌로 137

In [81]:
cfdata.to_csv('./data/cfdata.csv',encoding='utf-8')